# Generated by Django 4.1.13 on 2025-08-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atlas', '0002_alter_resource_managers_moodentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='sentiment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='note',
            field=models.TextField(blank=True, default='No note provided'),
            preserve_default=False,
        ),
    ]
