# Generated by Django 3.0.5 on 2025-09-01 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atlas', '0004_auto_20250901_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
