# Generated by Django 3.0.5 on 2025-09-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atlas', '0002_remove_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='membership',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium')], default='free', max_length=10),
        ),
        migrations.AlterField(
            model_name='resource',
            name='emotional_tone',
            field=models.CharField(choices=[('soft', ' Soft'), ('neutral', ' Neutral'), ('alert', 'Alert')], max_length=20),
        ),
    ]
